main: lts pow inv
clean: clean-lts clean-pow clean-inv
lts:
	ghc -o lstvezes lstvezes.hs
clean-lts: 
	rm lstvezes lstvezes.hi lstvezes.o
pow:
	ghc -o powlst powlst.hs
clean-pow: 
	rm powlst powlst.hi powlst.o
inv:
	ghc -o invertelst invertelst.hs
clean-inv:
	rm invertelst invertelst.hi invertelst.o