main: mutipleTwo firstN fibonacci
clean: clean-mutipleTwo clean-firstN clean-fibonacci
mutipleTwo: 
	ghc -o mutipleTwo mutipleTwo.hs
clean-mutipleTwo:
	rm mutipleTwo mutipleTwo.hi mutipleTwo.o
firstN:
	ghc -o firstN firstN.hs
clean-firstN:
	rm firstN firstN.hi firstN.o
fibonacci:
	ghc -o fibonacci fibonacci.hs
clean-fibonacci:
	rm fibonacci fibonacci.hi fibonacci.o