main: lst pow inv
clean: clean-lst clean-pow clean-inv
lst:
	ghc -o lstvezes lstvezes.hs
clean-lst: 
	rm lstvezes lstvezes.hi lstvezes.o
pow:
	ghc -o powlst powlst.hs
clean-pow: 
	rm powlst powlst.hi powlst.o
inv:
	ghc -o invertelst invertelst.hs
clean-inv:
	rm invertelst invertelst.hi invertelst.o